[package]
name = "uplift-cli"
version = "0.0.1"
authors = ["Dylan Owen <dyltotheo@gmail.com>"]
description = ""
readme = "Readme.md"
license = "MPL-2.0"
homepage = "https://github.com/dylanowen/uplift-cli"
repository = "https://github.com/dylanowen/uplift-cli"
edition = "2021"

[dependencies]
uplift-lib = { path = "../uplift_lib" }
log = "0.4.21"
env_logger = "0.11"

# async
tokio = { version = "1.37", features = ["rt-multi-thread"] }
futures = "0.3.30"

# Bluetooth support
btleplug = "0.11.5"
uuid = "1.8"

uom = "0.36"

# Error handling
anyhow = "1.0.82"
thiserror = "2.0"
